#!/usr/bin/env python
import argparse
import os
import pwd


def check(options):
    uid = options.get('uid')
    username = options.get('username')
    if uid is not None and username is not None:
        raise ValueError('Cannot specify uid and username')
    if uid is not None:
        password = pwd.getpwuid(uid)
    elif username is not None:
        password = pwd.getpwnam(username)
    else:
        password = pwd.getpwuid(os.getuid())

    # get a list at least 4 items long, hopefully split in the right pieces
    parts = (password.pw_gecos or "").split(',') + ([""] * 4)
    fullname = parts[0]
    room_number = parts[1]
    work_number = parts[2]
    home_number = parts[3]

    if options.get('fullname'):
        print(fullname)
    else:
        print(password.pw_uid, password.pw_name, fullname)

def main():
    pass

    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--uid',
        dest='uid',
        help='Numerical user ID',
        default=None
    )
    parser.add_argument(
        '--username',
        dest='username',
        help='Use this username',
        default=None
    )
    parser.add_argument(
        '--fullname',
        dest='fullname',
        help='Only print the full name',
        action='store_true',
        default=False
    )
    options = parser.parse_args()
    check(vars(options))

if __name__ == "__main__":
    main()
