#!/bin/bash
GIT_DIR=`git rev-parse --git-dir 2>/dev/null`
if [ -z "$GIT_DIR" ] ; then
    exit 1;
fi
if [ -f "$GIT_DIR/rebase-merge/interactive" ]; then
    echo "INTERACTIVE REBASING"
elif [ -d "$GIT_DIR/rebase-merge" ]; then
    echo "MERGING REBASE"
elif [ -d "$GIT_DIR/rebase-apply" ]; then
    if [ -f "$GIT_DIR/rebase-apply/rebasing" ]; then
        PROGRESS=`git ahead rebase-apply/onto`
        TOTAL=`git behind rebase-apply/orig-head`
        echo "REBASING ($PROGRESS/$TOTAL)"
    elif [ -f "$GIT_DIR/rebase-apply/applying" ]; then
        echo "APPLYING REBASE"
    else
        echo "REBASING"
    fi
fi
