#!/bin/bash
GIT_DIR=`git rev-parse --git-dir 2>/dev/null`
if [ -z "$GIT_DIR" ] ; then
    exit 1;
fi
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
ARGCOUNT=$#
if [ $ARGCOUNT -eq 1 ] ; then
    TARGET_BRANCH=$1
elif:
    TARGET_BRANCH=$(git config --get gitflow.branch.develop)
    if [ -z "${TARGET_BRANCH}" ] ; then
        TARGET_BRANCH=develop
    fi
fi

MERGE_BASE=$(git merge-base "${TARGET_BRANCH}" "${CURRENT_BRANCH}")
git rebase -i "${MERGE_BASE}"
