#!/bin/bash

if [ -n "${WORKON_HOME}" ] ; then
  if [ -e "${WORKON_HOME}/git-helpers/bin/activate" ] ; then
     # echo "activating ${WORKON_HOME}/git-helpers/bin/activate"
     source "${WORKON_HOME}/git-helpers/bin/activate"
   fi
fi
MY_DIR="$(dirname "${BASH_SOURCE}")"
function usage() {
  echo "Usage: git changelog FROM_REF TO_REF DEFAULT_VERSION_STRING"
  echo "FROM_REF is non-inclusive. Examples:"
  echo "git changelog 1.2.3 1.2.4  # logs after tag 1.2.3"
  echo "git changelog 1.2.3 HEAD"
  echo "git changelog 1.2.3 main"
  echo "git changelog since 1.2.3"
  echo "git changelog 1.2.3"
  echo "git changelog 1.2.3 main --verbose  # pass --verbose option to log_to_changelog.py"
  echo "git changelog 1.2.3 main --verbose --tags # pass --verbose and --tags option to log_to_changelog.py"
  echo "git changelog 1.2.3 -- --verbose  # pass --verbose option to log_to_changelog.py"
  echo "git changelog 1.2.3 -- \"Current\" --verbose"
  echo "git changelog 1.2.3 -- \"Current\" --tags"
  exit 1
}



GIT_DIR=`git rev-parse --git-dir 2>/dev/null`
if [ -z "$GIT_DIR" ] ; then
  echo "Current directory is not a git dir"
  usage
fi
ARGCOUNT=$#
if [ "$ARGCOUNT" -lt 1 ] ; then
  usage
fi
if [ "$ARGCOUNT" -eq 1 ] ; then
  REF_A="since"
  REF_B="${1}"
  shift
else
  REF_A="${1}"
  shift
  REF_B="${1}"
  shift
fi

if [ "${REF_A}" == "since" ] ; then
  REF_A="${REF_B}"
  REF_B="HEAD"
fi
if [ "${REF_B}" == "--" ] ; then
  REF_B="HEAD"
fi

if [ "$REF_A" == "--all" ] ; then
  RANGE="HEAD"
else
  SHA=$(git rev-parse "${REF_A}")
  SHB=$(git rev-parse "${REF_B}")
  RANGE="${SHA}^..${SHB}"
fi
# echo "SHAS A ${SHA}" B "${SHB} @ $@"

# echo git log "${SHA}^..${SHB}"
FORMAT="sha %H%ndate %as%nemail %ae%nname %an%nrefnames %D%nparents %P%nbody %B%n"

git log -z --format="${FORMAT}" "${RANGE}" \
   | python3.10 "${MY_DIR}/log_to_changelog.py" "$@"
