#!/bin/bash

if [ "${1}" == "--refresh" ] ; then
    git fetch --all
    echo "Refreshing the main branch from origin" 1>&2
    echo "was" 1>&2
    git rev-parse --abbrev-ref --symbolic-full-name origin/HEAD 1>&2
    git remote set-head origin -a 1>&2
fi

MAIN_NAME=$(git config --get gitflow.branch.main)
if [ -z "${MAIN_NAME}" ] ; then
    MAIN_NAME=$(git rev-parse --abbrev-ref --symbolic-full-name origin/HEAD | sed 's#^origin/##')
fi
if [ -z "${MAIN_NAME}" ] ; then
    MAIN_NAME=$(git for-each-ref --format='%(refname:short)' refs/heads refs/remotes/origin | grep '^main$' )
fi
if [ -z "${MAIN_NAME}" ] ; then
    MAIN_NAME=$(git for-each-ref --format='%(refname:short)' refs/heads refs/remotes/origin | grep '^origin/main$' | sed 's#^origin/##' )
fi
if [ -z "${MAIN_NAME}" ] ; then
    MAIN_NAME=$(git for-each-ref --format='%(refname:short)' refs/heads refs/remotes/origin | grep '^master' )
fi
if [ -z "${MAIN_NAME}" ] ; then
    MAIN_NAME=$(git for-each-ref --format='%(refname:short)' refs/heads refs/remotes/origin | grep '^origin/master' | sed 's#^origin/##' )
fi
if [ -z "${MAIN_NAME}" ] ; then
    MAIN_NAME="main"
fi
echo "${MAIN_NAME}"
