#!/bin/bash

if [ "${1}" == "--refresh" ] ; then
    git fetch --all
    echo "Refreshing the main branch from origin" 1>&2
    ORIGIN_HEAD=$(git rev-parse --abbrev-ref --symbolic-full-name origin/HEAD 2>/dev/null);
    if [ -n "${ORIGIN_HEAD}" ] ; then
        echo "origin/HEAD was ${ORIGIN_HEAD}" 1>&2
        git remote set-head origin -a 1>&2
    fi
fi

MAIN_NAME=$(git config --get gitflow.branch.main 2>/dev/null)
if [ -z "${MAIN_NAME}" ] ; then
    MAIN_NAME=$(git config --get gitflow.branch.master 2>/dev/null)
fi
if [ -z "${MAIN_NAME}" ] ; then
    MAIN_NAME=$(git rev-parse --abbrev-ref --symbolic-full-name origin/HEAD 2>/dev/null | sed 's#^origin/##' | head -n 1)
fi
if [ -z "${MAIN_NAME}" ] ; then
    MAIN_NAME=$(git for-each-ref --format='%(refname:short)' refs/heads refs/remotes/origin 2>/dev/null | grep '^main$' | head -n 1)
fi
if [ -z "${MAIN_NAME}" ] ; then
    MAIN_NAME=$(git for-each-ref --format='%(refname:short)' refs/heads refs/remotes/origin 2>/dev/null | grep '^origin/main$' | sed 's#^origin/##' | head -n 1)
fi
if [ -z "${MAIN_NAME}" ] ; then
    MAIN_NAME=$(git for-each-ref --format='%(refname:short)' refs/heads refs/remotes/origin 2>/dev/null | grep '^master' | head -n 1)
fi
if [ -z "${MAIN_NAME}" ] ; then
    MAIN_NAME=$(git for-each-ref --format='%(refname:short)' refs/heads refs/remotes/origin 2>/dev/null | grep '^origin/master' | sed 's#^origin/##' | head -n 1)
fi
if [ -z "${MAIN_NAME}" ] ; then
    MAIN_NAME="main"
fi
echo "${MAIN_NAME}"
