#!/bin/bash
GIT_DIR=`git rev-parse --git-dir 2>/dev/null`
if [ -z "$GIT_DIR" ] ; then
    exit 1;
fi
GIT_USER_NAME=`git config user.name`
GIT_USER_EMAIL=`git config user.email`
if [ -z "$GIT_USER_NAME" ]; then
    E_FULLNAME=`gecos --fullname | quote`
    echo
    echo "$(tput setaf 1)No username set for git: git config user.name $E_FULLNAME $(tput sgr0)"
fi
if [ -z "$GIT_USER_EMAIL" ]; then
    echo
    echo -n "$(tput setaf 1)"
    echo -n "No email set for git."
    echo " Guessing your email..."
    if [ -z "$EMAIL" ]; then
        if [ -z "$EMAIL" ]; then
            if [ -f ~/.forward ]; then
                EMAIL=`cat ~/.forward | head -n 1`
            else
                USERNAME=`whoami`
                if [ -f /etc/mailname ] ; then
                    HOSTNAME=`cat /etc/mailname`
                else
                    HOSTNAME=`hostname`
                fi
                EMAIL="$USERNAME@$HOSTNAME"
            fi
        fi
    fi
    E_EMAIL=`echo $EMAIL | quote`
    echo "git config user.email $E_EMAIL"
    echo "$(tput sgr0)"
fi
MASTER=`git for-each-ref --format='%(refname:short)' refs/heads refs/remotes/origin | grep ^master$`
DEVELOP=`git for-each-ref --format='%(refname:short)' refs/heads refs/remotes/origin | grep ^develop$`
ORIGIN_MASTER=`git for-each-ref --format='%(refname:short)' refs/heads refs/remotes/origin | grep ^origin/master$`
if [ -n "$DEVELOP" -a -n "$MASTER" ] ; then
    BEHIND=`git behind develop master`
    IGNORE=`git config sanity.ignore.develop.master`
    if [ -z "$IGNORE" -a "$BEHIND" -gt 0 ] ; then
        echo
        echo -n "$(tput setaf 1)"
        echo -n "develop is behind master by $BEHIND commits"
        echo "$(tput sgr0)"
    fi
fi
if [ -n "$DEVELOP" -a -n "$ORIGIN_MASTER" ] ; then
    BEHIND=`git behind develop origin/master`
    IGNORE=`git config sanity.ignore.develop.origin.master`
    if [ -z "$IGNORE" -a "$BEHIND" -gt 0 ] ; then
        echo
        echo -n "$(tput setaf 1)"
        echo -n "develop is behind origin/master by $BEHIND commits"
        echo "$(tput sgr0)"
    fi
fi
if [ -n "$MASTER" -a -n "$ORIGIN_MASTER" ] ; then
    BEHIND=`git behind master origin/master`
    if [ "$BEHIND" -gt 0 ] ; then
        echo
        echo -n "$(tput setaf 1)"
        echo -n "master is behind origin/master by $BEHIND commits"
        echo "$(tput sgr0)"
    fi
fi
