#!/bin/bash

GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
if [ -z "$GIT_DIR" ] ; then
    exit 1;
fi
FROM=HEAD
TO=$(git main)

ARGCOUNT=$#
if [ $ARGCOUNT -eq 1 ] ; then
    TO="$1"
else
    if [ $ARGCOUNT -eq 2 ] ; then
        FROM="$1"
        TO="$2"
    else
        TO=$(git main)
    fi
fi
MERGEBASE=$(git merge-base "${FROM}" "${TO}")
TARGET=$(git log "${MERGEBASE}^..${TO}" | grep '^commit' | awk '{print $2}' | grep -B 1 "${MERGEBASE}" | head -n 1)
echo "rebasing ${MERGEBASE} onto ${TARGET}"
git rebase "${TARGET}"
