#!/bin/bash
GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
if [ -z "$GIT_DIR" ] ; then
    exit 1;
fi
GIT_USER_NAME=$(git config user.name)
GIT_USER_EMAIL=$(git config user.email)
if [ -z "$GIT_USER_NAME" ]; then
    E_FULLNAME=$(gecos --fullname | quote)
    echo
    echo "$(tput setaf 1)No username set for git: git config user.name $E_FULLNAME $(tput sgr0)"
fi
if [ -z "$GIT_USER_EMAIL" ]; then
    echo
    echo -n "$(tput setaf 1)"
    echo -n "No email set for git."
    echo " Guessing your email..."
    if [ -z "$EMAIL" ]; then
        if [ -z "$EMAIL" ]; then
            if [ -f ~/.forward ]; then
                EMAIL=$(cat ~/.forward | head -n 1)
            else
                USERNAME=$(whoami)
                if [ -f /etc/mailname ] ; then
                    HOSTNAME=$(cat /etc/mailname)
                else
                    HOSTNAME=$(hostname)
                fi
                EMAIL="$USERNAME@$HOSTNAME"
            fi
        fi
    fi
    E_EMAIL=$(echo $EMAIL | quote)
    echo "git config user.email $E_EMAIL"
    echo "$(tput sgr0)"
fi
REMOTE=$(git remote)
if [ -n "$REMOTE" ] ; then
    _MAIN=$(git main)
    MAIN=$(git for-each-ref --format='%(refname:short)' refs/heads refs/remotes/origin | grep '^'"${_MAIN}"'$')
    DEVELOP=$(git for-each-ref --format='%(refname:short)' refs/heads refs/remotes/origin | grep "^develop$")
    ORIGIN_MAIN=$(git for-each-ref --format='%(refname:short)' refs/heads refs/remotes/origin | grep "^origin/${_MAIN}"'$')
    if [ -n "$DEVELOP" -a -n "${MAIN}" ] ; then
        BEHIND=$(git behind develop "${MAIN}")
        IGNORE=$(git config "sanity.ignore.develop.${MAIN}")
        if [ -z "$IGNORE" -a "${BEHIND}" -gt 0 ] ; then
            echo
            echo -n "$(tput setaf 1)"
            echo -n "develop is behind ${MAIN} by ${BEHIND} commits"
            echo "$(tput sgr0)"
        fi
    fi
    if [ -n "$DEVELOP" -a -n "$ORIGIN_MAIN" ] ; then
        BEHIND=$(git behind develop "${ORIGIN_MAIN}")
        IGNORE=$(git config "sanity.ignore.develop.origin.${MAIN}")
        if [ -z "$IGNORE" -a "${BEHIND}" -gt 0 ] ; then
            echo
            echo -n "$(tput setaf 1)"
            echo -n "develop is behind ${ORIGIN_MAIN} by ${BEHIND} commits"
            echo "$(tput sgr0)"
        fi
    fi
    if [ -n "${MAIN}" -a -n "$ORIGIN_MAIN" ] ; then
        BEHIND=$(git behind "${MAIN}" "${ORIGIN_MAIN}")
        if [ "${BEHIND}" -gt 0 ] ; then
            echo
            echo -n "$(tput setaf 1)"
            echo -n "${MAIN} is behind ${ORIGIN_MAIN} by ${BEHIND} commits"
            echo "$(tput sgr0)"
        fi
    fi
fi
